### ISSUE TITLE
Does it work with k3d?

### ISSUE THREAD

**Issue by saada** [rpardini/docker-registry-proxy#111]
Hello 👋🏽 

Thank you for your project.
I tried setting it up with [k3d](https://k3d.io/v4.4.8/usage/guides/registries/) with no success.

Documenting how to integrate it would be fantastic.
Any guidance on this?

**Comment by saada** [comment]
Found a solution.

```sh
# docker-registry-proxy
docker run -d --name registry-proxy --restart=always \
-v /tmp/registry-proxy/mirror_cache:/docker_mirror_cache \
-v /tmp/registry-proxy/certs:/ca \
rpardini/docker-registry-proxy:0.6.4 

# k3d
k3d cluster create
--registry-config registries.yaml \
--env HTTPS_PROXY=http://registry-proxy:3128/@server[*] \
--volume "/tmp/registry-proxy/certs:/etc/ssl/certs"
```

```yaml
# registries.yaml
mirrors:
  registry-proxy:3128:
    endpoint:
      - https://registry-proxy:3128
  docker.io:
    endpoint:
      - https://registry-proxy:3128
  quay.io:
    endpoint:
      - https://registry-proxy:3128
  ghcr.io:
    endpoint:
      - https://registry-proxy:3128
  gitlab.com:
    endpoint:
      - https://registry-proxy:3128
  registry.opensource.zalan.do:
    endpoint:
      - https://registry-proxy:3128
configs:
  registry-proxy:
    tls:
      ca_file: /etc/ssl/certs/ca.crt
```
