### ISSUE TITLE
proxy connection is very slow

### ISSUE THREAD

**Issue by ahmadalli** [rpardini/docker-registry-proxy#42]
Hi. Thank you for the project :)

I have issue with download speed. I have 1Gbps network on my node and download speed between proxy and client node is fine (tested with `iperf`). But when I try to download a container (e.g. `docker pull ubuntu`) it's very slow (less than 1Mbps)

I've tried docker-compose:

```yaml
version: '3.8'
services:
  registry_proxy:
    image: rpardini/docker-registry-proxy:0.3.0
    restart: always
    ports:
      - 3128:3128
    environment:
      REGISTRIES: mcr.microsoft.com
      DEBUG: "true"
    volumes:
      - ./docker_mirror_cache:/docker_mirror_cache
      - ./docker_mirror_certs:/ca
```

and command:

```bash
docker run --rm --name docker_registry_proxy -it \
       -p 0.0.0.0:3128:3128 \
       -v $(pwd)/docker_mirror_cache:/docker_mirror_cache \
       -v $(pwd)/docker_mirror_certs:/ca \
       -e REGISTRIES="mcr.microsoft.com" \
       -e DEBUG="true" \
       rpardini/docker-registry-proxy:0.3.0
```

on both cases, I'm seeing these logs on the server:

```
HIT [05/May/2020:04:44:23 +0000] "/v2/library/ubuntu/blobs/sha256:d51af753c3d3a984351448ec0f85ddafc580680fd6dfce9f4b09fdb367ee1e3e" 200 28556247 "HOST:registry-1.docker.io" "PROXY-HOST:registry-1.docker.io" "UPSTREAM:-"
127.0.0.1:60242: clientconnect
HIT [05/May/2020:04:44:24 +0000] "/v2/library/ubuntu/blobs/sha256:fee5db0ff82f7aa5ace63497df4802bbadf8f2779ed3e1858605b791dc449425" 200 163 "HOST:registry-1.docker.io" "PROXY-HOST:registry-1.docker.io" "UPSTREAM:-"
127.0.0.1:60242: Certificate verification error for 127.0.0.1: self signed certificate in certificate chain (errno: 19, depth: 2)
127.0.0.1:60242: Ignoring server verification error, continuing with connection
127.0.0.1:60242: clientdisconnect
```
