### ISSUE TITLE
Add docker-compose example

### ISSUE THREAD

**Issue by tivotyro** [rpardini/docker-registry-proxy#69]
Attempting to launch the rpardini/docker-registry-proxy from docker-compose.  Creates the certs, and then throws and error and halts while testing */etc/nginx/nginx.conf*.

### Versions Tried
```
0.3.0
0.4.0
0.5.0
0.6.0
latest
```

### docker-compose.yml
```
version: '3.7'

services:
  docker_registry_proxy:
    image: rpardini/docker-registry-proxy:0.6.0
    env_file:
      - ./secrets.env
    environment:
      - CACHE_MAX_SIZE=256g
      - ENABLE_MANIFEST_CACHE=true
    volumes:
      - /mnt/easystore/docker_mirror_cache:/docker_mirror_cache
      - ./docker-mirror-certs:/ca
    ports:
      - 3128:3128
```

### secrets.env
```
# Used By Docker Hub Proxy
REGISTRIES="auth.docker.io"
AUTH_REGISTRIES="auth.docker.io:mmxca:********"
``` 

### Generated Output
```
docker_registry_proxy_1  | Adding certificate for registry: docker.caching.proxy.internal
docker_registry_proxy_1  | Adding certificate for registry: registry-1.docker.io
docker_registry_proxy_1  | Adding certificate for registry: auth.docker.io
docker_registry_proxy_1  | Adding certificate for registry: auth.docker.io
docker_registry_proxy_1  | INFO: Will create certificate with names DNS:docker.caching.proxy.internal,DNS:registry-1.docker.io,DNS:auth.docker.io,DNS:auth.docker.io
docker_registry_proxy_1  | INFO: No CA was found. Generating one.
docker_registry_proxy_1  | INFO: *** Please *** make sure to mount /ca as a volume -- if not, everytime this container starts, it will regenerate the CA and nothing will work.
docker_registry_proxy_1  | Generating RSA private key, 4096 bit long modulus (2 primes)
docker_registry_proxy_1  | .................................................++++
docker_registry_proxy_1  | .....++++
docker_registry_proxy_1  | e is 65537 (0x010001)
docker_registry_proxy_1  | INFO: generate CA cert with key and self sign it: 4ff17d5c6e57 2020.12.01 18:06
docker_registry_proxy_1  | INFO: Generate IA key
docker_registry_proxy_1  | INFO: Create a signing request for the IA: 4ff17d5c6e57 2020.12.01 18:06
docker_registry_proxy_1  | INFO: Sign the IA request with the CA cert and key, producing the IA cert
docker_registry_proxy_1  | INFO: Initialize the serial number for signed certificates
docker_registry_proxy_1  | INFO: Create the key (w/o passphrase..)
docker_registry_proxy_1  | INFO: Create the signing request, using extensions
docker_registry_proxy_1  | INFO: Sign the request, using the intermediate cert and key
docker_registry_proxy_1  | INFO: Concatenating fullchain.pem...
docker_registry_proxy_1  | INFO: Concatenating fullchain_with_key.pem
docker_registry_proxy_1  | Adding Auth for registry '"auth.docker.io' with user 'mmxca'.
docker_registry_proxy_1  | Upstream SSL certificate verification enabled.
docker_registry_proxy_1  | Testing nginx config...
docker_registry_proxy_1  | 2020/12/01 18:06:29 [emerg] 57#57: unexpected "a" in /etc/nginx/docker.auth.map:1
docker_registry_proxy_1  | nginx: [emerg] unexpected "a" in /etc/nginx/docker.auth.map:1
docker_registry_proxy_1  | nginx: configuration file /etc/nginx/nginx.conf test failed
```

Let me know if there is anything I can do to help troubleshoot
